# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='mobno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
